spring.application.name=connect-hub-be
server.servlet.context-path=/api

# 2. DATABASE CONNECTION CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/connecthub?TimeZone=UTC
spring.datasource.username=sa
spring.datasource.password=sapassword
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.jdbc.time_zone=UTC